
language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    
    - build-tools-30.0.2
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
    - $ANDROID_TARGET
    
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
      - intel-android-extra-license.+

before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew
  #- wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  #- unzip -qq gradle-6.5-bin.zip
  #- export GRADLE_HOME=$PWD/gradle-6.5
  #- export PATH=$GRADLE_HOME/bin:$PATH
  
  #- gradle -v
  
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &
 
